# Folosește versiunea LTS de Node.js
FROM node:22.17-alpine

# Setează directorul de lucru
WORKDIR /usr/src/app

# Copiază fișierele de configurare
COPY ./apps/node-app/package*.json ./

# Instalează dependențele (poți folosi npm ci dacă ai lockfile)
RUN npm install

# Copiază codul aplicației
COPY ./apps/node-app .

# Expune portul aplicației
EXPOSE 8080

# Comandă de rulare
CMD ["npm", "start"]